###Добавление продукта 1
POST http://localhost:8080/store/order/add
Content-Type: application/json

{
"nameProduct": "test1",
"price": 100
}
###Добавление продукта 2
POST http://localhost:8080/store/order/add
Content-Type: application/json

{
"nameProduct": "test2",
"price": 150
}
###Добавление продукта 3
POST http://localhost:8080/store/order/add
Content-Type: application/json

{
"nameProduct": "test5",
"price": 200
}
###Добавление продукта 4
POST http://localhost:8080/store/order/add
Content-Type: application/json

{
"nameProduct": "test4",
"price": 250
}
###Получение списка содержимого карзины
GET http://localhost:8080/store/order/get
